source "https://rubygems.org"

gem "bourbon"
gem "coffee-script"
gem "jekyll"
gem "jekyll-assets"
gem "jekyll-haml"
gem "neat"
gem "octopress-autoprefixer"
gem "sass"
gem "uglifier"
gem "mini_magick"
